spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:cloudnotes}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, prometheus
  endpoint:
    info:
      enabled: true
    prometheus:
      enabled: true
    health:
      enabled: true
